### ISSUE TITLE
Undefined args.aux_net

### ISSUE THREAD

**Issue by wangkiw** [ZixuanKe/PyContinual#11]
Hi ~
 
Thanks for your framework for continual Learning in NLP!  But I find that the `args.aux_net` in https://github.com/ZixuanKe/PyContinual/blob/9beb0daced7746aaf83be4e99b8aa764b0c46056/src/run.py#L231 is never defined. 

Best,
Qi-Wei

**Comment by ZixuanKe** [comment]
Thanks for pointing this out. Indeed, this argument is not used and can be removed. We are working on a cleaner version of PyContinual (see the [developing branch](https://github.com/ZixuanKe/PyContinual/tree/dev/v1.0.0)). Please stay tuned.

**Comment by wangkiw** [comment]
Thanks for the reply, looking forward to the new version!
