### ISSUE TITLE
What does the config parameter use_imp do?

### ISSUE THREAD

**Issue by itsmemala** [ZixuanKe/PyContinual#16]
Hi,

I'm trying to implement the ctr model. I'm wondering what the use_imp signifies. I see it is used as below in networks\base\my_transformers.py:
" if args.use_imp:
            from networks.base.adapters import BertAdapterCapsuleMaskImp as BertAdapterCapsuleMask
            from networks.base.adapters import BertAdapterCapsuleImp as BertAdapterCapsule
        else:
            from networks.base.adapters import BertAdapterCapsuleMask
            from networks.base.adapters import BertAdapterCapsule"

What is the difference between the 2 sets of imports? For replicating the results from the paper "achieving forgetting prevention and knowledge transfer in continual learning", which import should I use here?

**Comment by ZixuanKe** [comment]
Thank you so much for your interest.

``use_impt`` simply means the ``ctr`` model. See https://github.com/ZixuanKe/PyContinual/blob/54dd15de566b110c9bc8d8316205de63a4805190/src/load_base_args.py/#L159. 

If you set ``use_predefine_args`` and ``baseline``==ctr, it should automatically set the hyper-parameters.

We understand the name is not intuitive and are working on developing a more readable [version](https://github.com/ZixuanKe/PyContinual/tree/dev/v1.0.0). Feel free to let us know if there are further questions.
