### ISSUE TITLE
Naming reasons for semantic and tsv capsules for B-CL and CTR

### ISSUE THREAD

**Issue by Vyralator** [ZixuanKe/PyContinual#18]
Hi,

I was curious why in the code for the CTR and B-CL the capsules are named tsv and semantic, if I understand correctly these are TCL and KCL from the paper respectively.
I couldn't find references to those names in any of the literature so I wanted to ask if those are just to improve code readability and where the names have their origins.

**Comment by ZixuanKe** [comment]
Thank you for bringing this to our attention. Yes, those are the two layers mentioned in the paper. 

The name can be confusing due to legacy reasons, but we plan to update it in a newer version. Thank you again, and please feel free to inform us of any other issues you may encounter.
