### ISSUE TITLE
Question on BERT Adapter implementation in "Achieving Forgetting Prevention and Knowledge Transfer in Continual Learning"

### ISSUE THREAD

**Issue by itsmemala** [ZixuanKe/PyContinual#19]
Hi, for each of the BERT Adapter based CL baselines implemented in the paper, were new adapter parameters added for each new task or was it constant or does this change by baseline? 
Specifically, in the BERT Adapter EWC implementation, I believe the number of parameters (excluding the task specific heads) remains constant (and shared across all tasks) from start to end of the task-sequence. Fisher weights are then used to regularize the fixed-size adapter parameters. Is this right? If not, could you explain which are the parameters being regularized using fisher weights?

**Comment by itsmemala** [comment]
Another related question - in the fisher diagonal calculation (function: fisher_matrix_diag_bert) , what does the sbatch parameter stand for?

**Comment by ZixuanKe** [comment]
Thank you so much for your interest in our work.

>  for each of the BERT Adapter based CL baselines implemented in the paper, were new adapter parameters added for each new task or was it constant or does this change by baseline?

The adapter parameters remained the same, including the EWC implementation. So yes, your understanding is correct.

> in the fisher diagonal calculation (function: fisher_matrix_diag_bert) , what does the sbatch parameter stand for?

``sbatch`` refers to batch size for fisher computation, which is a hyperparameter
