### ISSUE TITLE
Baseline Hypeparameters CTR

### ISSUE THREAD

**Issue by J4nn4** [ZixuanKe/PyContinual#23]
Hello,

I am currently trying to reproduce the results of the paper "Achieving Forgetting Prevention and Knowledge
Transfer in Continual Learning".
Thanks to your answers, I was able to get the same results as in the paper for the CTR architecture.
However, I am currently trying to reproduce the results for the Adapter-BERT baseline architecture.
Unfortunately, I could not find the hyperparameters for the Adapter-BERT baseline model.
Could you please provide the information about the Adapter-BERT baseline hyperparameters used, specifically the bert_adapter_size?

Thank you very much in advance!

**Comment by ZixuanKe** [comment]
Hello,

Thank you for your interest in our project.

We use a large adapter size (2000) to ensure a fair comparison, as seen on: https://github.com/ZixuanKe/PyContinual/blob/main/src/config.py#L59

Generally, default values in ``config.py`` will be used for hyper-parameters that are not found in ``load_base_args.py``.
