### ISSUE TITLE
args for iterative routing

### ISSUE THREAD

**Issue by J4nn4** [ZixuanKe/PyContinual#24]
Hello,

in the code I found the implementation of iterative routing for capsules. Is it possible to start the CTR architecture with iterative routing? If so which parameters should be set in args to start this routing version? Do you happen to have some demo args available?

Thanks in advance!

**Comment by ZixuanKe** [comment]
Hi,

Thank you for your interest in our project.

Regarding "iterative routing", do you mean dynamic routing as described in the paper by Sabour et al., NeurIPS 2017? If you switch transfer routing in CTR to dynamic routing, it will result in B-CL, as noted in the ablation section of the CTR paper. B-CL is included in PyContinual so you can simply run B-CL for that particular setting.

I hope this helps.
