### ISSUE TITLE
Running CTR and B-CL takes a long time

### ISSUE THREAD

**Issue by rahmahkn** [ZixuanKe/PyContinual#25]
Hi! Thank you for your excellent work for PyContinual. I wonder why it takes a long time (3-7 days) to run CTR and B-CL with the bert_adapter backbone. I am using my dataset with 17 tasks of sentiment analysis and emotion classification. I would like to know your GPU specification or if you have experienced the same thing. Thanks!

**Comment by ZixuanKe** [comment]
Hi,

Thank you so much for your interest in our work.

It could be slow if you use the main branch as it lacks support for multi-node and fp16. You may try the dev branch to achieve faster speeds.
