### ISSUE TITLE
CTR ablation

### ISSUE THREAD

**Issue by J4nn4** [ZixuanKe/PyContinual#26]
Hello,

in your CTR work you have performed an extensive ablation study by running CTR without "-KSM" or without "-TSM".
Is the code for the ablation study available in the repository?
If yes, I would appreciate if you could help in specifying parameters needed to perform the ablation study without "KSM".
Thank you in advance!

**Comment by ZixuanKe** [comment]
Apologies for the delay. The code base doesn't currently include the ablation, but you can easily implement it using the following:

For "-KSM": Comment out line 102 in the adapters.py file: https://github.com/ZixuanKe/PyContinual/blob/main/src/networks/base/adapters.py#L102

For "-TSM": Comment out lines 107 to 122 in the adapters.py file found at this link: https://github.com/ZixuanKe/PyContinual/blob/main/src/networks/base/adapters.py#L107-L122

Please don't hesitate to reach out if you have any further questions.

**Comment by J4nn4** [comment]
Thank you very much, I will try it.
