### ISSUE TITLE
Can not find `./data_seq`

### ISSUE THREAD

**Issue by QingZhao-Code** [ZixuanKe/PyContinual#6]
I can not find `./data_seq` in the code schema，is this part not uploaded or can it be customized?

**Comment by ZixuanKe** [comment]
Hi,

Thank you so much for your interest.

The ``./data_seq`` has been changed to ``./data_prep`` in https://github.com/ZixuanKe/PyContinual/tree/main/src/data_prep.

Yes, it can be customized. Each line represents a sequence order and different tasks are separated by ``\t``.

Feel free to let us know if you have more questions.

**Comment by QingZhao-Code** [comment]
Thanks for your answer, this question can be closed.
