### ISSUE TITLE
Question for paper "Adapting BERT for Continual Learning of a Sequence of Aspect Sentiment Classification Tasks"

### ISSUE THREAD

**Issue by leducthanguet** [ZixuanKe/PyContinual#7]
![theory](https://user-images.githubusercontent.com/57605661/168036770-2091503a-56ad-4aa8-86cf-f39722213a9d.png)

**Comment by ZixuanKe** [comment]
Thank you so much for your interest.

Are you asking where the output of the first layer of TSM goes to? We have two layers in TSM, so it simply goes to the next layer. You can see the code here:

https://github.com/ZixuanKe/PyContinual/blob/main/src/networks/base/adapters.py#L440

Feel free to let us know if we are misunderstanding your question.

**Comment by leducthanguet** [comment]
Thank you for your answer.
