### ISSUE TITLE
Question for paper "Adapting BERT for Continual Learning of a Sequence of Aspect Sentiment Classification Tasks"

### ISSUE THREAD

**Issue by leducthanguet** [ZixuanKe/PyContinual#8]
In the Task Capsule Layer, each capsule represents a task and TCL prepares low-level features derived from each task. As such, a capsule is added to TCL for every new task. I don't understand whether the model only created capsule for a new task or it created capsule for all tasks when it learned a new tasks?

**Comment by ZixuanKe** [comment]
Thank you so much for your interest.

``The model only created a capsule for a new task`` is the case. The total number of capsules is the same as the total number of tasks.

In terms of implementation, we create all capsules at once before training. See 

https://github.com/ZixuanKe/PyContinual/blob/main/src/networks/base/adapters.py#L480

You can see the weight (``route_weights``) does the job.

**Comment by leducthanguet** [comment]
Thank you for your answer !!!
